COMPILER_PREFIX=arm-none-linux-gnueabihf-
CC=$(COMPILER_PREFIX)gcc
STRIP=$(COMPILER_PREFIX)strip
INCLUDES=-I../../../alsa/include

CXXFLAGS=-Ofast -mcpu=cortex-a9 -mtune=cortex-a9 -mfpu=neon -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -Wno-write-strings -Wno-unused-result -Wno-deprecated-declarations
LDFLAGS=-L../../../alsa/lib

all: sw10_alsadrv

sw10_alsadrv: sw10_alsadrv.c ../VLSG/VLSG.c ../VLSG/VLSG.h
	$(CC) $(CXXFLAGS) $(INCLUDES) $(LDFLAGS) -Wall -o sw10_alsadrv sw10_alsadrv.c ../VLSG/VLSG.c -I../VLSG -lasound -lpthread
	$(STRIP) sw10_alsadrv
	
.PHONY: clean
clean:
	rm -f sw10_alsadrv
