enum SOFTSYNTH { MUNT, FluidSynth};
int  ini_read_ini(char * fileName);
void ini_print_settings();
char ini_replace_char(char * str, int strLen, char old, char new);
void ini_bool (char * value, int          * dest);
void ini_int  (char * value, int          * dest);
void ini_uint (char * value, unsigned int * dest);
void ini_str  (char * key,   char * value,  char * dest, int max);
char ini_process_key_value_pair(char * key, char * value);
char ini_first_char(char * str, int len);
int  ini_parse_line(char * str, int len, char * key, int keymax, char * value, int valMax);
int  ini_read_loop (char * fileName, char * key, int keyMax, char * value, int valmax);
