COMPILER_PREFIX=arm-linux-gnueabihf-
CC=$(COMPILER_PREFIX)gcc
CXX=$(COMPILER_PREFIX)g++
STRIP=$(COMPILER_PREFIX)strip

CXXFLAGS=-Ofast -mcpu=cortex-a9 -mtune=cortex-a9 -mfpu=neon -mfloat-abi=hard -ftree-vectorize -funsafe-math-optimizations -Wno-write-strings -Wno-unused-result -Wno-deprecated-declarations 
LIBS=-lpthread -lmt32emu -lm -lasound

# LDFLAGS tells the linker where to find direct (-L) and indirect (-rpath-link) libraries
LDFLAGS=-L../build/mt32emu \
	-L../../../alsa/lib
        
INCLUDES=-I../../../alsa/include \
	-I../build/mt32emu/include/

OBJS=wav.o alsadrv.o

default: mt32d

$(XOBJ) $(OBJS): %.o: src/%.cpp
	$(CXX) -c $< -o $@ $(CXXFLAGS) $(INCLUDES)

mt32d: 	$(OBJS) src/console.cpp
	$(CXX) src/console.cpp -o mt32d $(CXXFLAGS) $(INCLUDES) $(LDFLAGS) $(OBJS) $(LIBS)
	$(STRIP) mt32d
clean:
	rm -f *.o *~

realclean:
	rm mt32d -f